parameters:
#    bolbo_blog.example.class: Bolbo\BlogBundle\Example

services:
#    bolbo_blog.example:
#        class: %bolbo_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
