parameters:
#    bolbo_blog.example.class: Bolbo\BlogBundle\Example

services:
    bolbo.blog.post_manager:
        class: Bolbo\BlogBundle\Manager\PostManager
        arguments:
            - @pomm
            - \Bolbo\Component\Model\Database\PublicSchema\PostModel