<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace \Bolbo\Component\Model\Database\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Post
 *
 * Structure class for relation public.post.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Post extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.post')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('author_id', 'int4')
            ->addField('category_id', 'int4')
            ->addField('title', 'varchar')
            ->addField('content', 'text')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('deleted_at', 'timestamp')
            ->addField('meta_title', 'varchar')
            ->addField('meta_description', 'varchar')
            ->addField('meta_keyword', 'varchar')
            ->addField('tag', 'json')
            ->addField('published', 'bool')
            ->addField('slug', 'varchar')
            ;
    }
}
